version: "3.8"
services:
  ambientweather:
    environment:
      # Required. The timezone the service is running in. For a list of valid timezone values
      # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
      # The value to use is in the "TZ database name" column.
      - TZ=America/Los_Angeles

      # Required. The port this service runs on.
      - PORT=8080

      # Required. The MAC address for the Ambient Weather station. This can be found in the awnet
      # application
      - STATION_MAC_ADDRESS=00:00:00:00

      # Required. The URL to the server, including the port number if not running on port 80.
      - MQTT_SERVER=http://192.168.1.1:1883

      # Optional. The username to log into the MQTT server with.
      - MQTT_USERNAME=mqtt

      # Optional. The password to log into the MQTT server with.
      - MQTT_PASSWORD=passwordgoeshere

      # Leave as-is unless you know what you are doing.
      - MQTT_REJECT_UNAUTHORIZED=false

    # Don't modify anything below this line unless you know what you are doing.
    ports:
      - "${PORT}:${PORT}"

    image: danecreekphotography/ambientweather2mqtt:latest
    restart: always
